# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  database: leposse_development
  pool: 5
  host: localhost
  user: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: leposse_test
  pool: 5
  host: localhost
  user: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: leposse_production
  pool: 5
  host: localhost
  user: postgres
  password: postgres
